import React from 'react';
import Header from '../../Layout/Header';
import { Table, Button, message } from "antd/lib/index";

class Scheduling extends React.Component {
    render() {
        const dataSource = [{
            key: '1',
            flightNo: 'DR6508',
            airlines: '芒市-昆明-芒市',
            trail: 'B7088',
            gate: '150',
            inPlace: '2010',
            arrival: '2018',
            departure: '2130',
            release: '',
            power: '',
            fangxing: '侯乔瀚',
            technician: '用户名',
            mechanic: '黄朝玟',
            attendant: '王鹏程',
            trainees: '用户名',
            category: '航后'
        }, {
            key: '2',
            flightNo: 'DR6504',
            airlines: '芒市-昆明-西双版纳',
            trail: 'B6109',
            gate: '156',
            inPlace: '2012',
            arrival: '2025',
            departure: '2205',
            release: '2130',
            power: '',
            fangxing: '钟家源',
            technician: '',
            mechanic: '黄朝玟',
            attendant: '邱坤、汪雨轩',
            trainees: '',
            category: '航前'
        }, {
            key: '3',
            flightNo: 'DR6504',
            airlines: '芒市-昆明-西双版纳',
            trail: 'B6109',
            gate: '156',
            inPlace: '2012',
            arrival: '2025',
            departure: '2205',
            release: '2130',
            power: '',
            fangxing: '钟家源',
            technician: '',
            mechanic: '黄朝玟',
            attendant: '邱坤、汪雨轩',
            trainees: '',
            category: '过站'
        }, {
            key: '4',
            flightNo: 'DR6504',
            airlines: '芒市-昆明-西双版纳',
            trail: 'B6109',
            gate: '156',
            inPlace: '2012',
            arrival: '2025',
            departure: '2205',
            release: '2130',
            power: '',
            fangxing: '钟家源',
            technician: '',
            mechanic: '黄朝玟',
            attendant: '邱坤、汪雨轩',
            trainees: '',
            category: 0
        }, {
            key: '5',
            flightNo: 'DR6504',
            airlines: '芒市-昆明-西双版纳',
            trail: 'B6109',
            gate: '156',
            inPlace: '2012',
            arrival: '2025',
            departure: '2205',
            release: '2130',
            power: '',
            fangxing: '钟家源',
            technician: '',
            mechanic: '黄朝玟',
            attendant: '邱坤、汪雨轩',
            trainees: '',
            category: 0
        }, {
            key: '6',
            flightNo: 'DR6504',
            airlines: '芒市-昆明-西双版纳',
            trail: 'B6109',
            gate: '156',
            inPlace: '2012',
            arrival: '2025',
            departure: '2205',
            release: '2130',
            power: '',
            fangxing: '钟家源',
            technician: '',
            mechanic: '黄朝玟',
            attendant: '邱坤、汪雨轩',
            trainees: '',
            category: 0
        }, {
            key: '7',
            flightNo: 'DR6504',
            airlines: '芒市-昆明-西双版纳',
            trail: 'B6109',
            gate: '156',
            inPlace: '2012',
            arrival: '2025',
            departure: '2205',
            release: '2130',
            power: '',
            fangxing: '钟家源',
            technician: '',
            mechanic: '黄朝玟',
            attendant: '邱坤、汪雨轩',
            trainees: '',
            category: 0
        }, {
            key: '8',
            flightNo: 'DR6504',
            airlines: '芒市-昆明-西双版纳',
            trail: 'B6109',
            gate: '156',
            inPlace: '2012',
            arrival: '2025',
            departure: '2205',
            release: '2130',
            power: '',
            fangxing: '钟家源',
            technician: '',
            mechanic: '黄朝玟',
            attendant: '邱坤、汪雨轩',
            trainees: '',
            category: 0
        }, {
            key: '9',
            flightNo: 'DR6504',
            airlines: '芒市-昆明-西双版纳',
            trail: 'B6109',
            gate: '156',
            inPlace: '2012',
            arrival: '2025',
            departure: '2205',
            release: '2130',
            power: '',
            fangxing: '钟家源',
            technician: '',
            mechanic: '黄朝玟',
            attendant: '邱坤、汪雨轩',
            trainees: '',
            category: 0
        }, {
            key: '10',
            flightNo: 'DR6504',
            airlines: '芒市-昆明-西双版纳',
            trail: 'B6109',
            gate: '156',
            inPlace: '2012',
            arrival: '2025',
            departure: '2205',
            release: '2130',
            power: '',
            fangxing: '钟家源',
            technician: '',
            mechanic: '黄朝玟',
            attendant: '邱坤、汪雨轩',
            trainees: '',
            category: 0
        }, {
            key: '11',
            flightNo: 'DR6504',
            airlines: '芒市-昆明-西双版纳',
            trail: 'B6109',
            gate: '156',
            inPlace: '2012',
            arrival: '2025',
            departure: '2205',
            release: '2130',
            power: '',
            fangxing: '钟家源',
            technician: '',
            mechanic: '黄朝玟',
            attendant: '邱坤、汪雨轩',
            trainees: '',
            category: 0
        }, {
            key: '12',
            flightNo: 'DR6504',
            airlines: '芒市-昆明-西双版纳',
            trail: 'B6109',
            gate: '156',
            inPlace: '2012',
            arrival: '2025',
            departure: '2205',
            release: '2130',
            power: '',
            fangxing: '钟家源',
            technician: '',
            mechanic: '黄朝玟',
            attendant: '邱坤、汪雨轩',
            trainees: '',
            category: 0
        }, {
            key: '13',
            flightNo: 'DR6504',
            airlines: '芒市-昆明-西双版纳',
            trail: 'B6109',
            gate: '156',
            inPlace: '2012',
            arrival: '2025',
            departure: '2205',
            release: '2130',
            power: '',
            fangxing: '钟家源',
            technician: '',
            mechanic: '黄朝玟',
            attendant: '邱坤、汪雨轩',
            trainees: '',
            category: 0
        }, {
            key: '14',
            flightNo: 'DR6504',
            airlines: '芒市-昆明-西双版纳',
            trail: 'B6109',
            gate: '156',
            inPlace: '2012',
            arrival: '2025',
            departure: '2205',
            release: '2130',
            power: '',
            fangxing: '钟家源',
            technician: '',
            mechanic: '黄朝玟',
            attendant: '邱坤、汪雨轩',
            trainees: '',
            category: 0
        }, {
            key: '15',
            flightNo: 'DR6504',
            airlines: '芒市-昆明-西双版纳',
            trail: 'B6109',
            gate: '156',
            inPlace: '2012',
            arrival: '2025',
            departure: '2205',
            release: '2130',
            power: '',
            fangxing: '钟家源',
            technician: '',
            mechanic: '黄朝玟',
            attendant: '邱坤、汪雨轩',
            trainees: '',
            category: 0
        }];

        const columns = [{
            title: '航班号',
            dataIndex: 'key',
        }, {
            title: '航班号',
            dataIndex: 'flightNo',
            key: 'flightNo'
        }, {
            title: '航线',
            dataIndex: 'airlines',
        }, {
            title: '飞机号',
            dataIndex: 'trail',
        }, {
            title: '停机位',
            dataIndex: 'gate',
        }, {
            title: '到位时间',
            dataIndex: 'inPlace',
        }, {
            title: '进港时间',
            dataIndex: 'arrival',
        }, {
            title: '离港时间',
            dataIndex: 'departure',
        }, {
            title: '放行时间',
            dataIndex: 'release',
            render: (record) => {
                console.log(record);
                if (record) {
                    return record;
                } else {
                    return <Button onClick={
                        () => {
                            message.success("你点击了放行！");
                        }
                    }>放行</Button>;
                }
            }
        }, {
            title: '电源车/桥电',
            dataIndex: 'power',
        }, {
            title: '放行人员',
            dataIndex: 'fangxing',
        }, {
            title: '技术员',
            dataIndex: 'technician',
        }, {
            title: '机械员',
            dataIndex: 'mechanic',
        }, {
            title: '勤务员',
            dataIndex: 'attendant',
        }, {
            title: '学员',
            dataIndex: 'trainees',
        }, {
            title: '类别',
            dataIndex: 'category',
        }];

        return (
            <div>
                <Header />
                    <div style={{ padding: '0 50px',  margin: '16px 0' }}>
                        <Table dataSource={dataSource} columns={columns} size="small" pagination={false} />
                    </div>
            </div>
        );
    }
}

export default Scheduling;